import type { ThemesConfig } from "./types";

/**
 * Default theme options for light and dark themes.
 */
export const DEFAULT_THEME_OPTIONS = {
  light: {
    background: "hsl(0, 0%, 100%)",
    foreground: "hsl(0, 0%, 3.9%)",
    card: "hsl(0, 0%, 100%)",
    "card-foreground": "hsl(0, 0%, 3.9%)",
    popover: "hsl(0, 0%, 100%)",
    "popover-foreground": "hsl(0, 0%, 3.9%)",
    primary: "hsl(0, 0%, 9%)",
    "primary-foreground": "hsl(0, 0%, 98%)",
    secondary: "hsl(0, 0%, 96.1%)",
    "secondary-foreground": "hsl(0, 0%, 9%)",
    muted: "hsl(0, 0%, 96.1%)",
    "muted-foreground": "hsl(0, 0%, 45.1%)",
    accent: "hsl(0, 0%, 96.1%)",
    "accent-foreground": "hsl(0, 0%, 9%)",
    destructive: "hsl(0, 84.2%, 60.2%)",
    "destructive-foreground": "hsl(0, 0%, 98%)",
    border: "hsl(0, 0%, 89.8%)",
    input: "hsl(0, 0%, 89.8%)",
    ring: "hsl(0, 0%, 3.9%)",
  },
  dark: {
    background: "hsl(0, 0%, 3.9%)",
    foreground: "hsl(0, 0%, 98%)",
    card: "hsl(0, 0%, 3.9%)",
    "card-foreground": "hsl(0, 0%, 98%)",
    popover: "hsl(0, 0%, 3.9%)",
    "popover-foreground": "hsl(0, 0%, 98%)",
    primary: "hsl(0, 0%, 98%)",
    "primary-foreground": "hsl(0, 0%, 9%)",
    secondary: "hsl(0, 0%, 14.9%)",
    "secondary-foreground": "hsl(0, 0%, 98%)",
    muted: "hsl(0, 0%, 14.9%)",
    "muted-foreground": "hsl(0, 0%, 63.9%)",
    accent: "hsl(0, 0%, 14.9%)",
    "accent-foreground": "hsl(0, 0%, 98%)",
    destructive: "hsl(0, 62.8%, 30.6%)",
    "destructive-foreground": "hsl(0, 0%, 98%)",
    border: "hsl(0, 0%, 14.9%)",
    input: "hsl(0, 0%, 14.9%)",
    ring: "hsl(0, 0%, 83.1%)",
  },
} satisfies ThemesConfig;

/**
 * Array of named colors supported in CSS.
 */
export const NAMED_COLORS_ARRAY = [
  // CSS Level 1 colors
  "black",
  "silver",
  "gray",
  "white",
  "maroon",
  "red",
  "purple",
  "fuchsia",
  "green",
  "lime",
  "olive",
  "yellow",
  "navy",
  "blue",
  "teal",
  "aqua",

  // CSS Level 2/3 colors
  "aliceblue",
  "antiquewhite",
  "aqua",
  "aquamarine",
  "azure",
  "beige",
  "bisque",
  "black",
  "blanchedalmond",
  "blue",
  "blueviolet",
  "brown",
  "burlywood",
  "cadetblue",
  "chartreuse",
  "chocolate",
  "coral",
  "cornflowerblue",
  "cornsilk",
  "crimson",
  "cyan",
  "darkblue",
  "darkcyan",
  "darkgoldenrod",
  "darkgray",
  "darkgreen",
  "darkgrey",
  "darkkhaki",
  "darkmagenta",
  "darkolivegreen",
  "darkorange",
  "darkorchid",
  "darkred",
  "darksalmon",
  "darkseagreen",
  "darkslateblue",
  "darkslategray",
  "darkslategrey",
  "darkturquoise",
  "darkviolet",
  "deeppink",
  "deepskyblue",
  "dimgray",
  "dimgrey",
  "dodgerblue",
  "firebrick",
  "floralwhite",
  "forestgreen",
  "fuchsia",
  "gainsboro",
  "ghostwhite",
  "gold",
  "goldenrod",
  "gray",
  "green",
  "greenyellow",
  "grey",
  "honeydew",
  "hotpink",
  "indianred",
  "indigo",
  "ivory",
  "khaki",
  "lavender",
  "lavenderblush",
  "lawngreen",
  "lemonchiffon",
  "lightblue",
  "lightcoral",
  "lightcyan",
  "lightgoldenrodyellow",
  "lightgray",
  "lightgreen",
  "lightgrey",
  "lightpink",
  "lightsalmon",
  "lightseagreen",
  "lightskyblue",
  "lightslategray",
  "lightslategrey",
  "lightsteelblue",
  "lightyellow",
  "lime",
  "limegreen",
  "linen",
  "magenta",
  "maroon",
  "mediumaquamarine",
  "mediumblue",
  "mediumorchid",
  "mediumpurple",
  "mediumseagreen",
  "mediumslateblue",
  "mediumspringgreen",
  "mediumturquoise",
  "mediumvioletred",
  "midnightblue",
  "mintcream",
  "mistyrose",
  "moccasin",
  "navajowhite",
  "navy",
  "oldlace",
  "olive",
  "olivedrab",
  "orange",
  "orangered",
  "orchid",
  "palegoldenrod",
  "palegreen",
  "paleturquoise",
  "palevioletred",
  "papayawhip",
  "peachpuff",
  "peru",
  "pink",
  "plum",
  "powderblue",
  "purple",
  "rebeccapurple",
  "red",
  "rosybrown",
  "royalblue",
  "saddlebrown",
  "salmon",
  "sandybrown",
  "seagreen",
  "seashell",
  "sienna",
  "silver",
  "skyblue",
  "slateblue",
  "slategray",
  "slategrey",
  "snow",
  "springgreen",
  "steelblue",
  "tan",
  "teal",
  "thistle",
  "tomato",
  "turquoise",
  "violet",
  "wheat",
  "white",
  "whitesmoke",
  "yellow",
  "yellowgreen",
] as const;
